package com.cpu.process;

public enum ProcessTask {
    ATTITUDE_ESTIMATION,
    ATTITUDE_CONTROL,
    RATE_CONTROL,
    MOTOR_MIXER,
    GPS_PARSER,
    BAROMETER_HANDLE,
    MAGNETOMETER_HANDLE,
    RC_RECEIVER,
    AUTO_LANDING,
    FAILSAFE_HANDLER,
    BATTERY_MONITOR,
    TEMPERATURE_MONITOR
}
